### ISSUE TITLE
No check for when f(initial())

### ISSUE THREAD

**Issue by sjoelund** [modelica/Modelica-Compliance#20]
There is no test testing that `when f(initial()) then` is disallowed in 3.2r1. There is even one test using `when not initial() then` (WhenPriority.mo).

**Comment by FrenkelJ** [comment]
What did you mean with `when f(initial()) then` is disallowed in 3.2r1. 
Do you mean usage of initial() in a function inside when is dissallowed or do you mean the when branch is not activ during initialisation?

**Comment by HansOlsson** [comment]
I was also going to comment on this; when f(initial()) then is legal, but works in a way that may differ from the expected.
