### ISSUE TITLE
ModelicaCompliance.Equations.For.VariableRange is incorrect

### ISSUE THREAD

**Issue by miscco** [modelica/Modelica-Compliance#27]
The test ModelicaCompliance.Equations.For.VariableRange is incorrect, as the supposedly false behavior seems in agreement with the spec.

```modelica
	Integer x[3];
	Integer y[3]={1, 2, 3};
	equation
		for i in y loop
		  x[i] = y[i]; 
		end for;
```
As ModelicaSpec 8.3.2. states explicitely in example 3 this is legal. Similar to the test ModelicaCompliance.Algorithms.For.VariableRange

Is it meant, that the array ``y`` should change its size, which is indeed invalid?

**Comment by perost** [comment]
8.3.2 states:
>The expression of a for-equation shall be a parameter expression.
y is not a parameter expression, and thus illegal.

**Comment by miscco** [comment]
Comming back to this, i think that y should be either a constant or a parameter and not a variable

**Comment by FrenkelJ** [comment]
As Spec states and @perost already mentioned
> The expression of a for-equation shall be a parameter expression
the test ModelicaCompliance.Equations.For.VariableRange has to fail. The fact that the dimension of y is a constant is not important because as range is the value of y used and not the dimension like for implicit iteration ranges.
