### ISSUE TITLE
ModelicaCompliance.Connections.Declarations.OperatorRecordEquations does not test that operator records are handled

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/Modelica-Compliance#53]
**Reported by hansolsson on 11 Oct 2013 09:58 UTC**
The testing for operator records in connections is a bit counter-intuitive. 

The functionality is tested - but not in the way one would assume.

The details are: Assume that the part about operator records in 9.2 is ignored. One would assume that OperatorRecordEquations test-case would fail, since it is intended to test that this functionality is implemented.

However, if one ignores operator record part of 9.2 the operator record will be split into primitive elements for OperatorRecordEquations; and since Complex use cartesian coordinates this will generate the correct flow-equations!

Thus the test-case OperatorRecordEquations does in fact not test that operator records generate operator-record-equations. 
However, it tests that if operator-record-equations are generated they are the correct ones.

Instead the test-cases OperatorRecordMissing... will instead detect this issue (at least it is highly likely).

It might be ok to keep this as it is.

Changing the Complex functions to detect it will result a non-additive group, which would make the model incorrect (and not something that a tool is likely to detect).

The only alternative I could see would be to switch to Polar coordinates, but addition in Polar coordinates is a bit messy.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/1321

**Comment by HansOlsson** [comment]
Since equality isn't overloaded we cannot have non-minimal representation of the operator record.

Thus the only possibility would be some weird "operator record" - either with a bias, or stranger (like addition for polar coordinates). I propose to skip that and focus on more realistic problems.
