### ISSUE TITLE
Checking models in models?

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/Modelica-Compliance#59]
**Reported by hansolsson on 13 Dec 2013 16:40 UTC**
There is an inconsistency in the test-suite influencing the design of many test-cases:
* In several cases the error is not in the model itself, but in a class within the model, e.g. ModelicaCompliance.Classes.Enumeration.EnumDuplicateLiteral
* However, also many correct test-cases contain bad models (e.g ModelicaCompliance.Components.Conditional.CompRemovalBalanced.A is unbalanced).
* And in some cases checking sub-models will (unless we do something really odd) detect an error without checking for the actual issue, e.g. ModelicaCompliance.Components.Variability.DiscreteSubCompBlock. This seems less urgent.

I assume the intent is that no model used in a correct test-case should have any relevant issues. 

Here is a partial list of the models with issues (mostly balancing):
ModelicaCompliance.Classes.Specialized.BlockInputOutput.B
ModelicaCompliance.Components.Conditional.CompRemovalBalanced.A
ModelicaCompliance.Components.Conditional.CompRemovalBalancedParam.A
ModelicaCompliance.Components.Prefixes.DiscreteValidClassType.M
ModelicaCompliance.Components.Prefixes.FlowValidClassType.M
ModelicaCompliance.Connections.Declarations.ArrayEquations.M
ModelicaCompliance.Connections.Declarations.ConnectArrays.M
ModelicaCompliance.Connections.Declarations.ConnectParamSubscript.M
ModelicaCompliance.Connections.Declarations.ConnectWholeDim.M
ModelicaCompliance.Connections.Declarations.OperatorRecordEquations.M
ModelicaCompliance.Connections.Declarations.SimpleEquations.M
ModelicaCompliance.Connections.Expandable.AugmentComplex.M
ModelicaCompliance.Connections.Expandable.FlowInConnectorInExpandable.M
ModelicaCompliance.Connections.Restrictions.ConnectConstants.M
ModelicaCompliance.Connections.Restrictions.ConnectParameters.M
ModelicaCompliance.Connections.Stream.InStreamTwoInside.A
ModelicaCompliance.Operators.Special.Cardinality.M
ModelicaCompliance.Scoping.MemberAccess.AccessAlgorithm.A 
(and similarly for all cases in MemberAccess).
ModelicaCompliance.Scoping.InnerOuter.DifferentPrefixes.A has a constant bound to a parameter! 

\---
Also found the following:
Isn't ModelicaCompliance.Components.Prefixes.DiscreteValidClassType incorrect due to using when into a model?

ModelicaCompliance.Connections.Expandable.ConnectDisjointExpandables lacks content!

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/1383

**Comment by modelica-trac-importer** [comment]
**Comment by perost on 10 Feb 2014 16:55 UTC**
Most of these issues should be solved now I believe. There are some remaining issues, see comments below.

Replying to [ticket:1383 hansolsson]:
> \* And in some cases checking sub-models will (unless we do something really odd) detect an error without checking for the actual issue, e.g. ModelicaCompliance.Components.Variability.DiscreteSubCompBlock. This seems less urgent.

This particular case tests that a variable assigned in a when-clause may not be defined in a block sub-component (to keep the property of balanced models). I can't come up with any way to write a model where this is the only error though, since breaking this rule makes the model unbalanced. Does anyone have any suggestions?   

> ModelicaCompliance.Components.Prefixes.FlowValidClassType.M

Does this one really have issues? It seems to me like FlowValidClassType.M has 4 unknowns and 2 equations + 2 flows. When checking the model in Dymola it seems like the issue is that cr.f is an output, but I don't understand why that would influence the balancing.

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 3 Mar 2014 13:04 UTC**
I also found the new case for this:
ModelicaCompliance.Redeclare.Flattening.InheritanceStream

Replying to [comment:1 perost]:
> Most of these issues should be solved now I believe. There are some remaining issues, see comments below.

Ok, I only found one of them remaining (in addition to the ones listed below): ModelicaCompliance.Classes.Specialized.BlockInputOutput
is not corrected - and I don't see how it can be corrected - except for the simple solution of not having "input"/"output" on connectors with "flow" (as I understand it is just to test that blocks have input/outputs).

The equation count is local equations plus variables that are input or flow.
There are 3 such variables - and 4 variables in the model, so there should only be one equation. On the other hand there are 2 output variables so one would expect there to be 2 equations - I see no way of correcting that.
 
> Replying to [ticket:1383 hansolsson]:
> > \* And in some cases checking sub-models will (unless we do something really odd) detect an error without checking for the actual issue, e.g. ModelicaCompliance.Components.Variability.DiscreteSubCompBlock. This seems less urgent.
> This particular case tests that a variable assigned in a when-clause may not be defined in a block sub-component (to keep the property of balanced models). I can't come up with any way to write a model where this is the only error though, since breaking this rule makes the model unbalanced. Does anyone have any suggestions?   

Well, one possibilty would be to declare that variable as an input connector - since it is possible to textually provide an equation for an input connector (except that the when-part makes it incorrect); while keeping the sub-model balanced.

I agree that it is not the nicest solution - but it should work.

Another possibility would be to remove that restriction(=no when-clauses giving values to variables form sub-components) from the spec as it doesn't seem to add much when we require balanced models.

> > ModelicaCompliance.Components.Prefixes.FlowValidClassType.M
> Does this one really have issues? It seems to me like FlowValidClassType.M has 4 unknowns and 2 equations + 2 flows. When checking the model in Dymola it seems like the issue is that cr.f is an output, but I don't understand why that would influence the balancing.

On second thought I agree on this.

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 3 Mar 2014 14:41 UTC**
Found that there is one more: ModelicaCompliance.Connections.Expandable.ConnectDisjointExpandables
(since it has two outputs that have binding equations and also are connected).

A simple solution is to change it to:
```
  model M
    connector RealInput = input Real;
    RealInput x;
    RealInput y;
    EC1 ec1;
    EC2 ec2;
  equation 
    connect(x, ec1.x);
    connect(y, ec2.y);
    connect(ec1, ec2);
  end M;

  M m;
equation 
  m.x=2;
  m.y=time;
```

**Comment by modelica-trac-importer** [comment]
**Comment by perost on 6 Mar 2014 13:19 UTC**
Fixes in [this commit](https://github.com/modelica-compliance/compliance/commit/ada1321813df44d26227e376e1e4a7d26a25d291).

Replying to [comment:2 hansolsson]:
> I also found the new case for this:
> ModelicaCompliance.Redeclare.Flattening.InheritanceStream

Fixed.

> Replying to [comment:1 perost]:
> > Most of these issues should be solved now I believe. There are some remaining issues, see comments below.
> 
> Ok, I only found one of them remaining (in addition to the ones listed below): ModelicaCompliance.Classes.Specialized.BlockInputOutput
> is not corrected - and I don't see how it can be corrected - except for the simple solution of not having "input"/"output" on connectors with "flow" (as I understand it is just to test that blocks have input/outputs).

The spec says "each connector component of a block must have prefixes input and/or output for all connector variables.". The issue with this test was simply that I missed the "for all connector variables" part. I fixed the test by putting input/output on the connector variables instead of the connector components. There is also a BlockNoDirection test that checks that missing input/output is flagged as an error, but this test is accidentally correct.

> > Replying to [ticket:1383 hansolsson]:
> > > \* And in some cases checking sub-models will (unless we do something really odd) detect an error without checking for the actual issue, e.g. ModelicaCompliance.Components.Variability.DiscreteSubCompBlock. This seems less urgent.
> > This particular case tests that a variable assigned in a when-clause may not be defined in a block sub-component (to keep the property of balanced models). I can't come up with any way to write a model where this is the only error though, since breaking this rule makes the model unbalanced. Does anyone have any suggestions?   
> 
> Well, one possibilty would be to declare that variable as an input connector - since it is possible to textually provide an equation for an input connector (except that the when-part makes it incorrect); while keeping the sub-model balanced.

Fixed as suggested.

Replying to [comment:3 hansolsson]:
> Found that there is one more: ModelicaCompliance.Connections.Expandable.ConnectDisjointExpandables
> (since it has two outputs that have binding equations and also are connected).

Fixed as suggested.

**Comment by HansOlsson** [comment]
It seems this has now been fixed.
