### ISSUE TITLE
ModelicaCompliance.Scoping.InnerOuter.MissingInnerAdded

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/Modelica-Compliance#60]
**Reported by eldjillali&#46;talbi on 19 Dec 2013 16:51 UTC**
This test example checks that missing "inner" is added automatically during translation, if an annotation for it is specified. But the specification says "the tool may also temporarily automatically add the corresponding inner component during translation" (3.3 section 18.7). So the tool is not forced to add this inner prefix during translation, and this test should not be present in the compliance test suite.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/1385

**Comment by HansOlsson** [comment]
The test-suite was now updated to 3.4; so this is no longer an issue.
We could change in the maintenance branch, but the text in 3.2r2 was so confusing that it is unclear what to do.
