### ISSUE TITLE
SizeNestedInvalid is incorrectly marked as shouldPass = true

### ISSUE THREAD

**Issue by maltelenz** [modelica/Modelica-Compliance#70]
I believe this should say `shouldPass = false`, as is also indicated by the name of the class:

https://github.com/modelica/Modelica-Compliance/blob/8a91e75d8a26acc4de30fc0e5d5e9db83c970bd6/ModelicaCompliance/Connections/Restrictions/SizeNestedInvalid.mo#L20

**Comment by kabdelhak** [comment]
The connector is not balanced, but equation wise this should be balanced. We have an equation for each potential variable (`p.v = {1.0, 2.0, 3.0}, x= 4.0`) and the flows will get set to zero because they are not connected. 7 variables and 7 equations, am i missing something? Maybe the name is just wrong.

**Comment by HansOlsson** [comment]
> I believe this should say `shouldPass = false`, as is also indicated by the name of the class:
> 
> https://github.com/modelica/Modelica-Compliance/blob/8a91e75d8a26acc4de30fc0e5d5e9db83c970bd6/ModelicaCompliance/Connections/Restrictions/SizeNestedInvalid.mo#L20

Yes, looking more there's also a `SizeNestedValid `without the `x` in the connector (which therefore should be ok), so it makes sense that this one was changed to be invalid.

**Comment by maltelenz** [comment]
> The connector is not balanced, but equation wise this should be balanced. We have an equation for each potential variable (`p.v = {1.0, 2.0, 3.0}, x= 4.0`) and the flows will get set to zero because they are not connected. 7 variables and 7 equations, am i missing something? Maybe the name is just wrong.

It references the section 9.3.1, which says:

> For each non-partial non-expandable connector class the number of flow variables shall be equal to the number  of  variables  that  are  neither parameter, constant, input, output, stream nor flow.

So I'm sticking with my original statement that this model is invalid, as the name suggests :)

**Comment by kabdelhak** [comment]
> > For each non-partial non-expandable connector class the number of flow variables shall be equal to the number  of  variables  that  are  neither parameter, constant, input, output, stream nor flow.
> 
> So I'm sticking with my original statement that this model is invalid, as the name suggests :)

Ah that is true. But if we enforce that rule in general we will get some problems in the MSL.
If i see it correctly [Frame.mo](https://github.com/modelica/ModelicaStandardLibrary/blob/master/Modelica/Mechanics/MultiBody/Interfaces/Frame.mo) for example is not balanced by this rule. But that probably is another discussion entirely.

**Comment by HansOlsson** [comment]
> > > For each non-partial non-expandable connector class the number of flow variables shall be equal to the number  of  variables  that  are  neither parameter, constant, input, output, stream nor flow.
> > 
> > 
> > So I'm sticking with my original statement that this model is invalid, as the name suggests :)
> 
> Ah that is true. But if we enforce that rule in general we will get some problems in the MSL.
> If i see it correctly [Frame.mo](https://github.com/modelica/ModelicaStandardLibrary/blob/master/Modelica/Mechanics/MultiBody/Interfaces/Frame.mo) for example is not balanced by this rule. But that probably is another discussion entirely.

The quote above was shortened. It is followed by:
"The number of variables of an overdetermined type or record class (see Section 9.4.1) is the size of the output
argument of the corresponding equalityConstraint() function."
which handles the frame-connectors.
