### ISSUE TITLE
MissingInner no longer valid

### ISSUE THREAD

**Issue by jespermattsson** [modelica/Modelica-Compliance#8]
As of the resolution of https://trac.modelica.org/Modelica/ticket/1551, ModelicaCompliance.Scoping.InnerOuter.MissingInner should no longer fail. 
(And additionally, MissingInnerAdded was invalid from the beginning, since the spec previously said that a tool _was allowed_ to automatically add the declaration.)

**Comment by HansOlsson** [comment]
I agree that this should be changed. However, the test-suite is currently for Modelica 3.2r2 and that rule was added in Modelica 3.4 (as far as I recall). I would propose fix the outstanding issues for Modelica 3.2 compliance first and then start on later versions (with different branches).

However, I will also add something that should fail even with the updated rule: two outer declarations of the same component using different classes.
